### ISSUE TITLE
dom not ready

### ISSUE THREAD

**Issue by Farrukhw** [l1xnan/obsidian-better-export-pdf#229]
Hi,
On one document, although it says, `dom not ready`, however, it is still able to give me a preview:
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4318266/d54ce65f-cc22-4e75-af5c-5eb990576a3a)
and exporting the pdf awesomely.

However, on the other similar document, it is continuously saying "dom not ready" and unable to show any preview and can't Export:
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/4318266/a9ce6d36-d4a6-46b0-a307-2d733915c151)

Please find the .md files with Prefixes "Exporting..." and "Not Exporting..." to test and verify on your side.

[Not Exporting, Mean, Median, Mod. The measure of Central Tendency.md](https://github.com/user-attachments/files/15531553/Not.Exporting.Mean.Median.Mod.The.measure.of.Central.Tendency.md)
[Exporting, Variance and Standard Deviations - The Measures of Dispersion.md](https://github.com/user-attachments/files/15531555/Exporting.Variance.and.Standard.Deviations.-.The.Measures.of.Dispersion.md)

**Comment by l1xnan** [comment]
I tested the export in my own Obsidian, and it works fine. This issue is most likely due to a conflict with other plugins. Could you press `ctrl+shift+i` to open the console and check for any error messages? Additionally, you can enable debug mode to further inspect if there are any errors in the rendering preview modal.
![image](https://github.com/l1xnan/obsidian-better-export-pdf/assets/6105390/1efa2266-2d12-40e3-8513-6580fb3aea5d)

**Comment by Farrukhw** [comment]
Finally, I solved this by disabling the plugin `obsidian-metatable`, as it is referenced in the log.

**Comment by l1xnan** [comment]
The issue seems to be here. 
https://github.com/arnau/obsidian-metatable/blob/df6b59af4b57e2219ef6c5e8e5bd956356da116e/src/plugin.ts#L88-L89
This plugin has been archived, so there's no way to submit a PR, You can fix and compile it yourself.
Additionally, I noticed that the official export feature does not directly throw an error. It's unclear how the official plugin handles exceptions from third-party plugins. If I find out, there might be a better solution.

**Comment by l1xnan** [comment]
close https://github.com/l1xnan/obsidian-better-export-pdf/commit/04d01f7dafbdcd76cee01c2591ea781185609246
